import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { auditDerivativeReceipt, DerivativeAuditError } from '../scripts/audit-ww1-derivative.mjs';

const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
const glb = label => { const json = Buffer.from(JSON.stringify({ asset: { version: '2.0', generator: label }, scenes: [{ nodes: [] }], scene: 0 }).padEnd(84, ' ')), bytes = Buffer.alloc(20 + json.length); bytes.writeUInt32LE(0x46546c67); bytes.writeUInt32LE(2, 4); bytes.writeUInt32LE(bytes.length, 8); bytes.writeUInt32LE(json.length, 12); bytes.writeUInt32LE(0x4e4f534a, 16); json.copy(bytes, 20); return bytes; };
const root = await mkdtemp(join(tmpdir(), 'ww1-derivative-'));
const reportIndex = process.argv.indexOf('--report'), reportPath = reportIndex >= 0 ? resolve(process.argv[reportIndex + 1]) : null;

async function writeJson(path, value) { await mkdir(dirname(path), { recursive: true }); await writeFile(path, `${JSON.stringify(value, null, 2)}\n`); return readFile(path); }
async function buildFixture(directory) {
  await mkdir(directory, { recursive: true }); const providerBytes = glb('provider-rejected'), finalBytes = glb('authored-correction');
  const providerGlbPath = join(directory, 'provider.glb'), finalPath = join(directory, 'final.glb'), recipePath = join(directory, 'recipe.json'), decisionPath = join(directory, 'decision.json'), auditPath = join(directory, 'a6-audit.json'), providerReceiptPath = join(directory, 'provider-receipt.json'), receiptPath = join(directory, 'derivative-receipt.json');
  await writeFile(providerGlbPath, providerBytes); await writeFile(finalPath, finalBytes); const operations = ['rebuild receiver', 'author sockets', 'create LODs']; let recipeBytes = await writeJson(recipePath, { schemaVersion: 1, kind: 'ww1-derivative-correction-recipe', assetKey: 'test_asset', sourceAssetKey: 'provider_base', version: '1.0.0', operations });
  const evidence = [];
  for (const name of ['front.png', 'side.png', 'back.png', 'clay.png']) { const path = join(directory, name), bytes = Buffer.from(name); await writeFile(path, bytes); evidence.push({ path, bytes: bytes.length, sha256: sha256(bytes) }); }
  const contextPath = join(directory, 'review-context.json'), contextBytes = await writeJson(contextPath, { note: 'offline review evidence' }); evidence.push({ path: contextPath, bytes: contextBytes.length, sha256: sha256(contextBytes) });
  const decision = overrides => ({ schemaVersion: 1, kind: 'ww1-derivative-quality-decision', assetKey: 'test_asset', sourceAssetKey: 'provider_base', finalSha256: sha256(finalBytes), reviewer: 'independent-reviewer', status: 'accepted', finalAccepted: true, evidenceSha256s: evidence.map(item => item.sha256), ...overrides });
  const a6 = overrides => ({ schemaVersion: 1, role: 'weapon', scope: 'asset-bytes-audit', runtimeAccepted: false, manifestSha256: null, valid: true, files: [{ assetKey: 'test_asset', path: finalPath, valid: true, sha256: sha256(finalBytes), metrics: { bytes: finalBytes.length, triangles: 12, nodes: 3 }, issues: [] }], ...overrides });
  let decisionBytes = await writeJson(decisionPath, decision({}));
  let auditBytes = await writeJson(auditPath, a6({}));
  let providerReceipt = { schemaVersion: 1, assetKey: 'provider_base', attemptId: 'attempt-1', role: 'hero-weapon', state: 'review_rejected', source: { previewTaskId: 'provider-task-1' }, review: { status: 'rejected' }, reviewArtifacts: { model: { sha256: sha256(providerBytes), bytes: providerBytes.length } } };
  let providerReceiptBytes = await writeJson(providerReceiptPath, providerReceipt);
  let receipt = { schemaVersion: 1, kind: 'ww1-meshy-derived-authored', assetKey: 'test_asset', receiptRole: 'hero-weapon', sourceKind: 'meshy-derived-authored', source: { assetKey: 'provider_base', providerReceiptPath, providerReceiptSha256: sha256(providerReceiptBytes), providerState: 'review_rejected', attemptId: 'attempt-1', taskId: 'provider-task-1', glb: { path: providerGlbPath, bytes: providerBytes.length, sha256: sha256(providerBytes) } }, correction: { recipe: { path: recipePath, sha256: sha256(recipeBytes) }, author: 'asset-author', tool: 'Blender', toolVersion: '4.5.10', exporterVersion: 'Khronos glTF 4.5', operations, completedAt: '2026-09-11T17:00:00.000Z' }, final: { publicPath: '/assets/ww1/weapons/test-asset.glb', bytes: finalBytes.length, sha256: sha256(finalBytes) }, quality: { status: 'accepted', reviewer: 'independent-reviewer', decision: { path: decisionPath, sha256: sha256(decisionBytes) }, audit: { path: auditPath, sha256: sha256(auditBytes) }, evidence } };
  async function saveReceipt() { const bytes = await writeJson(receiptPath, receipt); return sha256(bytes); }
  const receiptHash = await saveReceipt();
  return { directory, providerGlbPath, finalPath, recipePath, decisionPath, auditPath, providerReceiptPath, receiptPath, providerReceipt, receipt, evidence, finalHash: sha256(finalBytes), receiptHash, decision, a6, saveReceipt,
    async saveProvider() { providerReceiptBytes = await writeJson(providerReceiptPath, providerReceipt); receipt.source.providerReceiptSha256 = sha256(providerReceiptBytes); return saveReceipt(); },
    async saveRecipe(value) { recipeBytes = await writeJson(recipePath, value); receipt.correction.recipe.sha256 = sha256(recipeBytes); return saveReceipt(); },
    async saveDecision(value) { decisionBytes = await writeJson(decisionPath, value); receipt.quality.decision.sha256 = sha256(decisionBytes); return saveReceipt(); },
    async saveAudit(value) { auditBytes = await writeJson(auditPath, value); receipt.quality.audit.sha256 = sha256(auditBytes); return saveReceipt(); } };
}
const options = fixture => ({ receiptPath: fixture.receiptPath, artifactPath: fixture.finalPath, expectedAssetKey: 'test_asset', expectedReceiptRole: 'hero-weapon', expectedPublicPath: '/assets/ww1/weapons/test-asset.glb', expectedReceiptSha256: fixture.receiptHash, expectedOutputSha256: fixture.finalHash, allowedRoots: [fixture.directory] });
async function rejects(name, mutate, code) { const fixture = await buildFixture(join(root, name)); const expected = await mutate(fixture) ?? options(fixture); await assert.rejects(auditDerivativeReceipt(expected), error => error instanceof DerivativeAuditError && error.code === code); return { name, code }; }

const scenarios = [];
try {
  const valid = await buildFixture(join(root, 'valid')); const accepted = await auditDerivativeReceipt(options(valid)); assert.equal(accepted.valid, true); assert.equal(accepted.providerState, 'review_rejected'); scenarios.push({ name: 'fully anchored accepted derivative', code: 'PASS' });
  scenarios.push(await rejects('receipt-anchor', async fixture => ({ ...options(fixture), expectedReceiptSha256: '0'.repeat(64) }), 'receipt_manifest_hash'));
  scenarios.push(await rejects('target-identity-anchor', async fixture => ({ ...options(fixture), expectedAssetKey: 'different_target' }), 'receipt_manifest_identity'));
  scenarios.push(await rejects('final-anchor', async fixture => { const changed = glb('changed-final'); await writeFile(fixture.finalPath, changed); fixture.receipt.final = { ...fixture.receipt.final, bytes: changed.length, sha256: sha256(changed) }; fixture.receiptHash = await fixture.saveReceipt(); return options(fixture); }, 'final_manifest_hash'));
  scenarios.push(await rejects('provider-not-rejected', async fixture => { fixture.providerReceipt.state = 'review_accepted'; fixture.receiptHash = await fixture.saveProvider(); return options(fixture); }, 'provider_rejection_lineage'));
  scenarios.push(await rejects('provider-secret', async fixture => { fixture.providerReceipt.MESHY_API_KEY = 'leaked-value'; fixture.receiptHash = await fixture.saveProvider(); return options(fixture); }, 'forbidden_provenance_content'));
  scenarios.push(await rejects('recipe-secret', async fixture => { fixture.receiptHash = await fixture.saveRecipe({ schemaVersion: 1, kind: 'ww1-derivative-correction-recipe', assetKey: 'test_asset', sourceAssetKey: 'provider_base', version: '1.0.0', operations: fixture.receipt.correction.operations, MESHY_API_KEY: 'leaked-value' }); return options(fixture); }, 'forbidden_provenance_content'));
  scenarios.push(await rejects('recipe-operation-mismatch', async fixture => { fixture.receiptHash = await fixture.saveRecipe({ schemaVersion: 1, kind: 'ww1-derivative-correction-recipe', assetKey: 'test_asset', sourceAssetKey: 'provider_base', version: '1.0.0', operations: ['unrelated operation'] }); return options(fixture); }, 'correction_recipe_mismatch'));
  scenarios.push(await rejects('same-author-reviewer', async fixture => { fixture.receipt.quality.reviewer = fixture.receipt.correction.author; fixture.receiptHash = await fixture.saveReceipt(); return options(fixture); }, 'independent_quality_required'));
  scenarios.push(await rejects('quality-pending', async fixture => { fixture.receipt.quality.status = 'candidate_pending_review'; fixture.receiptHash = await fixture.saveReceipt(); return options(fixture); }, 'independent_quality_required'));
  scenarios.push(await rejects('decision-rejected', async fixture => { fixture.receiptHash = await fixture.saveDecision(fixture.decision({ status: 'rejected', finalAccepted: false })); return options(fixture); }, 'independent_quality_required'));
  scenarios.push(await rejects('decision-conflict', async fixture => { fixture.receiptHash = await fixture.saveDecision(fixture.decision({ finalAccepted: false })); return options(fixture); }, 'independent_quality_required'));
  scenarios.push(await rejects('decision-extra-field', async fixture => { fixture.receiptHash = await fixture.saveDecision(fixture.decision({ selfAuthorized: true })); return options(fixture); }, 'invalid_quality_decision_shape'));
  scenarios.push(await rejects('decision-evidence-mismatch', async fixture => { fixture.receiptHash = await fixture.saveDecision(fixture.decision({ evidenceSha256s: fixture.evidence.slice(1).map(item => item.sha256) })); return options(fixture); }, 'independent_quality_required'));
  scenarios.push(await rejects('decision-auth', async fixture => { fixture.receiptHash = await fixture.saveDecision({ assetKey: 'test_asset', reviewer: 'independent-reviewer', status: 'accepted', note: 'Bearer leaked-token' }); return options(fixture); }, 'forbidden_provenance_content'));
  scenarios.push(await rejects('audit-invalid', async fixture => { fixture.receiptHash = await fixture.saveAudit(fixture.a6({ valid: false })); return options(fixture); }, 'accepted_a6_audit_required'));
  scenarios.push(await rejects('audit-missing-runtime-acceptance', async fixture => { const value = fixture.a6({}); delete value.runtimeAccepted; fixture.receiptHash = await fixture.saveAudit(value); return options(fixture); }, 'invalid_quality_audit_shape'));
  scenarios.push(await rejects('audit-extra-field', async fixture => { fixture.receiptHash = await fixture.saveAudit(fixture.a6({ selfAuthorized: true })); return options(fixture); }, 'invalid_quality_audit_shape'));
  scenarios.push(await rejects('audit-url', async fixture => { fixture.receiptHash = await fixture.saveAudit({ assetKey: 'test_asset', valid: true, outputSha256: fixture.finalHash, source: 'https://private.invalid/audit' }); return options(fixture); }, 'forbidden_provenance_content'));
  scenarios.push(await rejects('evidence-changed', async fixture => { await writeFile(fixture.evidence[0].path, 'changed'); return options(fixture); }, 'quality_evidence_hash'));
  scenarios.push(await rejects('evidence-url', async fixture => { const bytes = Buffer.from('{"source":"https://signed.example.invalid/private"}'); await writeFile(fixture.evidence[4].path, bytes); fixture.evidence[4] = { path: fixture.evidence[4].path, bytes: bytes.length, sha256: sha256(bytes) }; fixture.receiptHash = await fixture.saveDecision(fixture.decision({})); return options(fixture); }, 'forbidden_provenance_content'));
  scenarios.push(await rejects('evidence-aliases-decision', async fixture => { fixture.evidence[0] = { ...fixture.receipt.quality.decision, bytes: (await readFile(fixture.decisionPath)).length }; fixture.receiptHash = await fixture.saveDecision(fixture.decision({})); return options(fixture); }, 'quality_evidence_hash'));
  scenarios.push(await rejects('source-aliases-final', async fixture => { fixture.receipt.source.glb = { path: fixture.finalPath, bytes: (await readFile(fixture.finalPath)).length, sha256: fixture.finalHash }; fixture.providerReceipt.reviewArtifacts.model = { sha256: fixture.finalHash, bytes: fixture.receipt.source.glb.bytes }; fixture.receiptHash = await fixture.saveProvider(); return options(fixture); }, 'source_final_alias'));
  scenarios.push(await rejects('unknown-receipt-field', async fixture => { fixture.receipt.selfAuthorized = true; fixture.receiptHash = await fixture.saveReceipt(); return options(fixture); }, 'invalid_receipt_shape'));
  scenarios.push(await rejects('unowned-source', async fixture => { fixture.receipt.source.glb.path = resolve(fixture.directory, '..', 'outside.glb'); fixture.receiptHash = await fixture.saveReceipt(); return options(fixture); }, 'missing_file'));
  const binaryEvidence = await buildFixture(join(root, 'binary-evidence')); const binaryBytes = Buffer.from('https://binary-metadata.invalid/not-a-json-document'); await writeFile(binaryEvidence.evidence[0].path, binaryBytes); binaryEvidence.evidence[0] = { path: binaryEvidence.evidence[0].path, bytes: binaryBytes.length, sha256: sha256(binaryBytes) }; binaryEvidence.receiptHash = await binaryEvidence.saveDecision(binaryEvidence.decision({})); assert.equal((await auditDerivativeReceipt(options(binaryEvidence))).valid, true); scenarios.push({ name: 'binary evidence is hash-bound without text scanning', code: 'PASS' });
  const durable = reportPath ? await buildFixture(join(dirname(reportPath), 'derivative-fixture')) : valid, durableResult = await auditDerivativeReceipt(options(durable)); assert.equal(durableResult.valid, true);
  const rejected = reportPath ? await buildFixture(join(dirname(reportPath), 'derivative-fixture-rejected')) : await buildFixture(join(root, 'durable-rejected'));
  rejected.receiptHash = await rejected.saveDecision(rejected.decision({ status: 'rejected', finalAccepted: false }));
  await assert.rejects(auditDerivativeReceipt(options(rejected)), error => error instanceof DerivativeAuditError && error.code === 'independent_quality_required');
  const report = { verdict: 'PASS', scenarios, durable: { root: durable.directory, receiptPath: durable.receiptPath, artifactPath: durable.finalPath, expectedAssetKey: 'test_asset', expectedReceiptRole: 'hero-weapon', expectedPublicPath: '/assets/ww1/weapons/test-asset.glb', expectedReceiptSha256: durable.receiptHash, expectedOutputSha256: durable.finalHash, result: durableResult }, durableRejected: { root: rejected.directory, receiptPath: rejected.receiptPath, artifactPath: rejected.finalPath, expectedAssetKey: 'test_asset', expectedReceiptRole: 'hero-weapon', expectedPublicPath: '/assets/ww1/weapons/test-asset.glb', expectedReceiptSha256: rejected.receiptHash, expectedOutputSha256: rejected.finalHash, expectedError: 'independent_quality_required' } };
  if (reportPath) { await mkdir(dirname(reportPath), { recursive: true }); await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`); }
  console.log(JSON.stringify(report));
} finally { await rm(root, { recursive: true, force: true }); }
